name: CI

on:
  schedule:
    - cron: '0 */3 * * *'  # ⏰ Mỗi 3 giờ một lần (theo UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # Không dùng token mặc định

      - name: Run script
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Last run: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > timestamp.txt
          cat timestamp.txt >> README.md
          git config user.name "blwsy"
          git config user.email "lethanhofc@outlook.com"
          git add README.md timestamp.txt
          git commit -m "✅ Auto update at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
