name: CI

on:
  schedule:
    - cron: '0 */3 * * *'  # ⏰ Mỗi 3 giờ một lần
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # Không dùng token mặc định

      - name: Run script
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " " >> README.md
          git config user.name "blwsy"
          git config user.email "lethanhofc@outlook.com"
          git add README.md
          git commit -m "Always green!" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
